//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Movie_Catalog
{
    using System;
    using System.Collections.Generic;
    
    public partial class Favourite_Hated
    {
        public int FilmID { get; set; }
        public int UserID { get; set; }
        public int LikeOrDislike { get; set; }
    
        public virtual MainMovieList MainMovieList { get; set; }
        public virtual User User { get; set; }
    }
}
