//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Movie_Catalog
{
    using System;
    using System.Collections.Generic;
    
    public partial class MainMovieList
    {
        public MainMovieList()
        {
            this.Favourite_Hated = new HashSet<Favourite_Hated>();
        }
    
        public int ID { get; set; }
        public string Movie_Name { get; set; }
        public string File_Name { get; set; }
        public string File_Path { get; set; }
    
        public virtual ICollection<Favourite_Hated> Favourite_Hated { get; set; }
    }
}
